server:
  port: 8080

spring:
  config:
    import:
      - database-local.properties
      - front.properties
      - message.properties
      - mail.properties
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: ${DB.DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database-platform: ${DB.DIALECT}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: ${MAIL.HOST}
    port: ${MAIL.PORT}
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
          timeout: ${MAIL.TIME_OUT}
    username: ${MAIL.USER_NAME}
    password: ${MAIL.PASSWORD}
  data.redis:
    host: ${REDIS.HOST}
    port: ${REDIS.PORT}

logging:
  level:
    com.ssafy.sandbox: ${LOGGING_LEVEL:DEBUG}
